version: "3.5"

services:
  db:
    image: "postgres:13"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "wravel"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080